#index:
#    path: /
#    controller: App\Controller\DefaultController::index
index:
    path: /
    controller: App\Controller\MainController::index
homepage:
    path: /homepage
    controller: App\Controller\MainController::homepage
adddevice:
    path: /adddevice
    controller: App\Controller\DeviceController::adddevice
model:
    path: /model
    controller: App\Controller\DeviceController::model
type:
    path: /type
    controller: App\Controller\DeviceController::type
location:
    path: /location
    controller: App\Controller\DeviceController::location
protocollist:
    path: /protocollist
    controller: App\Controller\ProtocolController::protocollist
protocol:
    path: /protocol/{id}
    controller: App\Controller\ProtocolController::showprotocol
invoicing:
    path: /invoicing
    controller: App\Controller\DeviceController::invoicing
onservice:
    path: /onservice
    controller: App\Controller\DeviceController::onservice
devicehistory:
    path: /devicehistory
    controller: App\Controller\DeviceController::devicehistory
historybydate:
    path: /historybydate
    controller: App\Controller\DeviceController::historybydate
changesn:
    path: /changesn
    controller: App\Controller\DeviceController:changesn
addprotocol:
    path: /addprotocol
    controller: App\Controller\ProtocolController::addprotocol
finddevice:
    path: /finddevice
    controller: App\Controller\DeviceController::finddevice
gen_prot_ret:
    path: /gen_prot_ret
    controller: App\Controller\ProtocolController::genProtRet
man_prot_ret:
    path: /man_prot_ret
    controller: App\Controller\ProtocolController::manProtRet
get_person_loc:
    path: /get_person_loc
    controller: App\Controller\ProtocolController::getPersonLoc
addperson:
    path: /addperson
    controller: App\Controller\PersonController::addPerson
personhistory:
    path: /personhistory
    controller: App\Controller\PersonController::personHistory
get_type_models:
    path: /get_type_models
    controller: App\Controller\DeviceController::getTypeModels
devices_from_loc:
    path: /devices_from_loc
    controller: App\Controller\DeviceController::getDevicesFromLoc
devices_by_type_from_loc:
    path: /devices_by_type_from_loc
    controller: App\Controller\DeviceController::getDevicesByTypeFromLoc
sorted_models_by_type:
    path: /sorted_models_by_type
    controller: App\Controller\DeviceController::getSortedModelsByType
devices_to_fv:
    path: /devices_to_fv
    controller: App\Controller\DeviceController::getDevicesToFV
devices_on_service:
    path: /devices_on_service
    controller: App\Controller\DeviceController::getDevicesOnService
devices_by_sn:
    path: /devices_by_sn
    controller: App\Controller\DeviceController::getDevicesBySN
get_person_history:
    path: /get_person_history
    controller: App\Controller\PersonController::getPersonHistory
confirm_protocol:
    path: /confirm_protocol
    controller: App\Controller\ProtocolController::confirmProtocol
get_efficient_devices:
    path: /get_efficient_devices
    controller: App\Controller\ProtocolController::getEfficientDevices
reserve_devices:
    path: /reserve_devices
    controller: App\Controller\ProtocolController::reserveDevices
unreserve_devices:
    path: /unreserve_devices
    controller: App\Controller\ProtocolController::unreserveDevices
get_person_devices:
    path: /get_person_devices
    controller: App\Controller\ProtocolController::getPersonDevices
logout:
    path: /logout
    controller: App\Controller\MainController::logout